<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\lib\</BaseOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VL.Core" Version="2025.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Devices.LS2Lidar\Devices.LS2Lidar.csproj" />
  </ItemGroup>
</Project>
